package main

import (
	"context"
	"encoding/base64"
	"flag"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"time"
)

func main() {
	startTime := time.Now()
	dataDir := flag.String("data-dir", envOrDefault("RELAY_LLM_DATA", ""), "Data directory (default: ~/.config/relayLLM)")
	ollamaURL := flag.String("ollama-url", envOrDefault("OLLAMA_URL", "http://localhost:11434"), "Ollama base URL")
	openaiConfigPath := flag.String("openai-config", envOrDefault("OPENAI_CONFIG", ""), "Path to OpenAI-compatible endpoints config JSON (default: {data-dir}/openai_endpoints.json)")
	socketPath := flag.String("socket", envOrDefault("RELAY_LLM_SOCKET", ""), "Unix domain socket path for this listener. Defaults to {data-dir}/relayllm.sock. Used by direct clients in standalone mode and by relay (via manifest registration) when running under relay.")
	internalToken := flag.String("token", envOrDefault("RELAY_LLM_TOKEN", ""), "Bearer token required on every request. Empty → auto-generated random hex (printed at startup).")
	llamaServerPath := flag.String("llama-server-path", envOrDefault("LLAMA_SERVER_PATH", ""), "Path to llama-server binary (default: llama-server on PATH)")
	mlxServePath := flag.String("mlx-serve-path", envOrDefault("MLX_SERVE_PATH", ""), "Path to mlx-serve binary (default: mlx-serve on PATH)")
	routerPort := flag.String("router-port", envOrDefault("RELAY_ROUTER_PORT", ""), "Port for the unified OpenAI-compatible relay-router fronting managed servers (llama-server, mlx-serve) + OpenAI endpoints (empty to disable)")
	routerBind := flag.String("router-bind", envOrDefault("RELAY_ROUTER_BIND", "127.0.0.1"), "Bind address for the relay-router TCP listener. Set to 0.0.0.0 to accept connections from other hosts.")
	routerTLSCert := flag.String("router-tls-cert", envOrDefault("RELAY_LLM_ROUTER_TLS_CERT", ""), "TLS certificate file for the relay-router listener. Requires --router-tls-key; empty (with key also empty) serves plain http.")
	routerTLSKey := flag.String("router-tls-key", envOrDefault("RELAY_LLM_ROUTER_TLS_KEY", ""), "TLS private key file for the relay-router listener. Requires --router-tls-cert.")
	flag.Parse()

	if (*routerTLSCert == "") != (*routerTLSKey == "") {
		missing := "--router-tls-cert/RELAY_LLM_ROUTER_TLS_CERT"
		if *routerTLSCert != "" {
			missing = "--router-tls-key/RELAY_LLM_ROUTER_TLS_KEY"
		}
		slog.Error("relay router TLS requires both cert and key", "missing", missing)
		os.Exit(1)
	}

	if *dataDir == "" {
		dir, err := os.UserConfigDir()
		if err != nil {
			dir, _ = os.UserHomeDir()
		}
		*dataDir = filepath.Join(dir, "relayLLM")
	}
	if err := os.MkdirAll(*dataDir, 0700); err != nil {
		slog.Error("failed to create data directory", "path", *dataDir, "error", err)
		os.Exit(1)
	}

	// Listener address: relayLLM picks where it binds. relay (if running)
	// learns the path via manifest registration; standalone clients dial it
	// directly. Default keeps the socket under data-dir so it's discoverable.
	if *socketPath == "" {
		*socketPath = filepath.Join(*dataDir, "relayllm.sock")
	}
	// Bearer token: relayLLM picks its own. Auto-generated if unset so the
	// listener is never unauthenticated. Under relay the token travels via
	// manifest registration. For standalone direct-client use, pin it with
	// --token / RELAY_LLM_TOKEN — we deliberately do not log the
	// auto-generated value so it doesn't end up in shipped log files.
	tokenAutoGenerated := *internalToken == ""
	if tokenAutoGenerated {
		*internalToken = generateBearerToken()
	}

	slog.Info("starting relayLLM",
		"socket", *socketPath,
		"dataDir", *dataDir,
		"tokenAutoGenerated", tokenAutoGenerated)

	sessionStore := NewSessionStore(filepath.Join(*dataDir, "sessions"))
	perms := NewPermissionManager()
	sessions := NewSessionManager(sessionStore, perms)
	sessions.SetDataDir(*dataDir)

	// Load provider + pty config up front. Terminal subsystem needs the pty
	// map to seed defaults before serving requests.
	cfg, err := LoadConfig(*dataDir, *openaiConfigPath)
	if err != nil {
		slog.Error("failed to load config", "error", err)
		os.Exit(1)
	}
	sessions.SetPiConfig(cfg.Pi)
	if cfg.Pi.BinaryPath != "" {
		slog.Info("pi binary configured", "path", cfg.Pi.BinaryPath)
	}

	// Terminal subsystem.
	templateStore := NewTemplateStore(*dataDir)
	if err := templateStore.Load(cfg.PTY); err != nil {
		slog.Error("failed to load terminal templates", "error", err)
	}
	terminalLogDir := filepath.Join(*dataDir, "terminal_logs")
	if err := os.MkdirAll(terminalLogDir, 0700); err != nil {
		slog.Error("failed to create terminal log directory", "path", terminalLogDir, "error", err)
		os.Exit(1)
	}
	terminalMgr := NewTerminalManager(templateStore, terminalLogDir)

	// Daily log GC. 30 days time-based with a 500 MB byte cap as a safety
	// net. Runs immediately at startup to catch up after a long downtime,
	// then once per 24h. Idle process — no shutdown coordination needed.
	go func() {
		const (
			sweepAge      = 30 * 24 * time.Hour
			sweepMaxBytes = int64(500 * 1024 * 1024)
			sweepInterval = 24 * time.Hour
		)
		for {
			if removed, err := sweepTerminalLogs(terminalLogDir, sweepAge, sweepMaxBytes); err != nil {
				slog.Warn("terminal log sweep failed", "error", err)
			} else if removed > 0 {
				slog.Info("terminal log sweep", "removed", removed)
			}
			time.Sleep(sweepInterval)
		}
	}()

	// Daily GC: drop headless sessions/*.json older than 7d, then drop
	// pi-sessions/*.jsonl whose piSessionId is no longer referenced by
	// any survivor (1h cushion so we don't race a live pi writer).
	go func() {
		const (
			headlessAge   = 7 * 24 * time.Hour
			piOrphanAge   = 1 * time.Hour
			sweepInterval = 24 * time.Hour
		)
		sessionsDir := filepath.Join(*dataDir, "sessions")
		piDir := filepath.Join(*dataDir, "pi-sessions")
		for {
			removed, livePi, err := sweepSessions(sessionsDir, headlessAge)
			if err != nil {
				slog.Warn("session sweep failed", "error", err)
			} else if removed > 0 {
				slog.Info("session sweep", "removed", removed)
			}
			if livePi != nil {
				if removed, err := sweepOrphanedPiSessions(piDir, livePi, piOrphanAge); err != nil {
					slog.Warn("pi orphan sweep failed", "error", err)
				} else if removed > 0 {
					slog.Info("pi orphan sweep", "removed", removed)
				}
			}
			time.Sleep(sweepInterval)
		}
	}()

	wsHub := NewWSHub(sessions, perms, terminalMgr)
	sessions.SetEventSink(wsHub)
	perms.SetEventSink(wsHub)

	// Wire terminal I/O to WebSocket hub.
	terminalMgr.SetOutputHandler(func(terminalID string, data []byte) {
		wsHub.SendToTerminal(terminalID, map[string]interface{}{
			"type":       WSMsgTerminalOutput,
			"terminalId": terminalID,
			"data":       base64.StdEncoding.EncodeToString(data),
		})
	})
	terminalMgr.SetExitHandler(func(terminalID string, exitCode int) {
		wsHub.SendToTerminal(terminalID, map[string]interface{}{
			"type":       WSMsgTerminalExit,
			"terminalId": terminalID,
			"exitCode":   exitCode,
		})
	})

	// The Claude CLI hook subprocess (runs as the user) dials our Unix
	// socket and authenticates with the internal token.
	sessions.SetHookSocket(*socketPath)
	sessions.SetHookToken(*internalToken)
	sessions.SetOllamaURL(*ollamaURL)

	if len(cfg.OpenAI.Endpoints) > 0 {
		slog.Info("openai endpoints loaded", "count", len(cfg.OpenAI.Endpoints), "names", cfg.OpenAI.Names())
	}
	sessions.SetOpenAIConfig(cfg.OpenAI)
	var llamaManager *ServerManager
	if len(cfg.Llama.Models) > 0 {
		llamaManager = NewServerManager(llamaProfile, cfg.Llama, *llamaServerPath)
		llamaManager.StartIdleReaper()
		slog.Info("llama models configured", "count", len(cfg.Llama.Models), "binary", llamaManager.binaryPath)
	}
	sessions.SetLlamaManager(llamaManager)

	var mlxManager *ServerManager
	if len(cfg.Mlx.Models) > 0 {
		mlxManager = NewServerManager(mlxProfile, cfg.Mlx, *mlxServePath)
		mlxManager.StartIdleReaper()
		slog.Info("mlx models configured", "count", len(cfg.Mlx.Models), "binary", mlxManager.binaryPath)
	}
	sessions.SetMlxManager(mlxManager)

	var proxyRegistry *ProxyRegistry
	if len(cfg.OpenAI.Endpoints) > 0 {
		proxyRegistry = NewProxyRegistry(cfg.OpenAI)
	}
	sessions.SetProxyRegistry(proxyRegistry)

	// Slice order is the router's dispatch priority: llama wins alias
	// collisions with mlx.
	var managers []*ServerManager
	if llamaManager != nil {
		managers = append(managers, llamaManager)
	}
	if mlxManager != nil {
		managers = append(managers, mlxManager)
	}
	warnAliasShadowing(managers, cfg.OpenAI.Endpoints)
	warnVirtualModelConfig(cfg.Virtual, managers, cfg.OpenAI.Endpoints)

	routerAddr := routerListenAddr(*routerBind, *routerPort)
	// cfg.Router is passed straight into StartRelayRouter rather than set on
	// the router afterward — see StartRelayRouter's doc comment for why a
	// separate post-construction setter call raced the router's first
	// accepted connection.
	relayRouter := StartRelayRouter(routerAddr, managers, proxyRegistry, cfg.Virtual, cfg.Router, *routerTLSCert, *routerTLSKey)
	sessions.SetRouterPort(*routerPort)
	sessions.SetRouterHost(*routerBind)
	terminalMgr.SetPiOverlay(cfg.Pi, sessions.piOverlayInputs)

	mux := http.NewServeMux()
	RegisterSessionRoutes(mux, sessions)
	RegisterTerminalRoutes(mux, templateStore, terminalMgr)
	RegisterPermissionRoutes(mux, perms, sessions)
	RegisterModelRoutes(mux, *ollamaURL, proxyRegistry, llamaManager, mlxManager, cfg.Pi, sessions.piOverlayInputs)
	RegisterGeneratedImageRoutes(mux, *dataDir)
	RegisterStatusRoutes(mux, sessions, terminalMgr, llamaManager, mlxManager, startTime)
	mux.HandleFunc("/ws", wsHub.HandleUpgrade)

	// Build the handler chain. recoverMiddleware sits closest to the mux so it
	// catches panics from real handlers; bearerAuth sits in front so unauth
	// requests never reach a real handler (and never allocate a WS session).
	handler := bearerAuth(*internalToken, recoverMiddleware(mux))

	server := &http.Server{Handler: handler}

	if err := os.MkdirAll(filepath.Dir(*socketPath), 0o700); err != nil {
		slog.Error("failed to create socket parent dir", "path", *socketPath, "error", err)
		os.Exit(1)
	}
	// Remove any stale socket file from a previous crashed run.
	_ = os.Remove(*socketPath)
	listener, err := net.Listen("unix", *socketPath)
	if err != nil {
		slog.Error("failed to listen on socket", "path", *socketPath, "error", err)
		os.Exit(1)
	}
	if err := os.Chmod(*socketPath, 0o600); err != nil {
		slog.Warn("failed to chmod socket", "path", *socketPath, "error", err)
	}

	// Tell relay (if present) where to dispatch front-door traffic.
	// Standalone runs are a clean no-op. Run in a goroutine so a slow
	// relay-bridge round-trip doesn't delay the listener accepting traffic.
	go maybeRegisterManifest(*dataDir, *socketPath, *internalToken)

	// Graceful shutdown: drain HTTP requests, then clean up providers and terminals.
	go func() {
		sig := make(chan os.Signal, 1)
		signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)
		<-sig
		slog.Info("shutting down")

		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = server.Shutdown(ctx)
		_ = listener.Close()
		_ = os.Remove(*socketPath)
	}()

	slog.Info("listening", "socket", *socketPath)
	if err := server.Serve(listener); err != nil && err != http.ErrServerClosed {
		slog.Error("server error", "error", err)
		os.Exit(1)
	}

	// Server stopped — clean up background resources. Managers stop in
	// parallel so shutdown is bounded by one SIGTERM grace period, not one
	// per manager.
	sessions.StopAll()
	if relayRouter != nil {
		relayRouter.Close()
	}
	var wg sync.WaitGroup
	for _, mgr := range managers {
		wg.Add(1)
		go func() {
			defer wg.Done()
			mgr.StopAll()
		}()
	}
	wg.Wait()
	terminalMgr.StopAll()
	slog.Info("shutdown complete")
}

// warnAliasShadowing logs startup warnings for names the relay-router's
// dispatch order makes unreachable. Bare-alias collisions between managers
// are won by the earlier (higher-priority) manager. OpenAI endpoint models
// are only addressable as "{endpoint}/{id}", so an endpoint name equal to a
// bare alias collides with nothing — only an alias that itself contains "/"
// can intercept an endpoint model id.
func warnAliasShadowing(managers []*ServerManager, endpoints []OpenAIEndpoint) {
	for i, mgr := range managers {
		for _, alias := range mgr.Aliases() {
			for _, earlier := range managers[:i] {
				if earlier.HasAlias(alias) {
					slog.Warn("router: alias shadowed by a higher-priority manager; model unreachable via the router",
						"alias", alias, "shadowed", mgr.profile.Kind, "wins", earlier.profile.Kind)
					break
				}
			}
			if prefix, _, ok := strings.Cut(alias, "/"); ok {
				for _, ep := range endpoints {
					if ep.Name == prefix {
						slog.Warn("router: managed alias would intercept an openai endpoint model id of the same name",
							"alias", alias, "kind", mgr.profile.Kind, "endpoint", ep.Name)
					}
				}
			}
		}
	}
}

// warnVirtualModelConfig logs startup warnings for virtual-model
// misconfiguration that would otherwise only surface later as a confusing
// runtime 503 (or, worse, silently route to the wrong place). Mirrors
// warnAliasShadowing's dead-config detection, one layer up.
func warnVirtualModelConfig(virtual *VirtualLLMConfig, managers []*ServerManager, endpoints []OpenAIEndpoint) {
	if virtual == nil {
		return
	}
	seenNames := make(map[string]bool)
	for i := range virtual.Models {
		v := &virtual.Models[i]

		if seenNames[v.Name] {
			slog.Warn("router: two virtual models share a name; only the first definition is reachable",
				"name", v.Name)
		}
		seenNames[v.Name] = true

		for _, mgr := range managers {
			if mgr.HasAlias(v.Name) {
				// handleProxy checks managers before virtuals, so this name
				// can never reach the virtual branch.
				slog.Warn("router: virtual model name matches a managed alias; dispatch checks managers first so the virtual is unreachable",
					"name", v.Name, "shadowed-by-kind", mgr.profile.Kind)
			}
		}
		if strings.Contains(v.Name, "/") {
			// endpoint/id routing parses on the first "/", so a virtual name
			// containing one can intercept it.
			slog.Warn("router: virtual model name contains \"/\"; it can intercept endpoint/id routing",
				"name", v.Name)
		}

		usable := 0
		// Dispatches on classifyVirtualTarget — the same classification
		// candidatesForVirtual uses — rather than a hand-maintained switch of
		// its own. The two used to drift apart: this validator's first case
		// used to be "endpoint set, model not," which swallowed a target that
		// set endpoint (without model) *and* alias; candidatesForVirtual
		// checks alias second and routes that target fine via the alias, so
		// this validator flagged a virtual that actually works (code review
		// item 5). Sharing one classifier makes that drift impossible.
		for _, target := range v.Targets {
			switch classifyVirtualTarget(target) {
			case virtualTargetEndpoint:
				found := false
				for _, ep := range endpoints {
					if ep.Name == target.Endpoint {
						found = true
						break
					}
				}
				if !found {
					slog.Warn("router: virtual model target names an endpoint absent from openai.endpoints",
						"name", v.Name, "endpoint", target.Endpoint)
					continue
				}
				usable++
			case virtualTargetAlias:
				found := false
				for _, mgr := range managers {
					if mgr.HasAlias(target.Alias) {
						found = true
						break
					}
				}
				if !found {
					slog.Warn("router: virtual model target names an alias no manager has",
						"name", v.Name, "alias", target.Alias)
					continue
				}
				usable++
			default: // virtualTargetInvalid
				switch {
				case target.Endpoint != "" && target.Model == "":
					slog.Warn("router: virtual model target sets endpoint without model",
						"name", v.Name, "endpoint", target.Endpoint)
				case target.Model != "" && target.Endpoint == "" && target.Alias == "":
					slog.Warn("router: virtual model target sets model without endpoint",
						"name", v.Name, "model", target.Model)
				}
				// else: neither shape set at all — nothing specific to warn.
			}
		}
		if usable == 0 {
			slog.Warn("router: virtual model has no usable target; every request for it will fail",
				"name", v.Name)
		}
	}
}

func envOrDefault(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// routerListenAddr composes the relay-router's listen address from
// --router-bind and --router-port. An empty port means the router is
// disabled (StartRelayRouter treats "" as "don't listen"), so bind is
// irrelevant and deliberately not defaulted in that case.
func routerListenAddr(bind, port string) string {
	if port == "" {
		return ""
	}
	return net.JoinHostPort(bind, port)
}
