package main

import (
	"context"
	"encoding/base64"
	"flag"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"
	"time"
)

func main() {
	startTime := time.Now()
	dataDir := flag.String("data-dir", envOrDefault("RELAY_LLM_DATA", ""), "Data directory (default: ~/.config/relayLLM)")
	ollamaURL := flag.String("ollama-url", envOrDefault("OLLAMA_URL", "http://localhost:11434"), "Ollama base URL")
	openaiConfigPath := flag.String("openai-config", envOrDefault("OPENAI_CONFIG", ""), "Path to OpenAI-compatible endpoints config JSON (default: {data-dir}/openai_endpoints.json)")
	socketPath := flag.String("socket", envOrDefault("RELAY_LLM_SOCKET", ""), "Unix domain socket path for this listener. Defaults to {data-dir}/relayllm.sock. Used by direct clients in standalone mode and by relay (via manifest registration) when running under relay.")
	internalToken := flag.String("token", envOrDefault("RELAY_LLM_TOKEN", ""), "Bearer token required on every request. Empty → auto-generated random hex (printed at startup).")
	comfyuiURL := flag.String("comfyui-url", envOrDefault("COMFYUI_URL", ""), "ComfyUI base URL for image generation (empty to disable)")
	llamaServerPath := flag.String("llama-server-path", envOrDefault("LLAMA_SERVER_PATH", ""), "Path to llama-server binary (default: llama-server on PATH)")
	routerPort := flag.String("router-port", envOrDefault("RELAY_ROUTER_PORT", ""), "Port for the unified OpenAI-compatible relay-router fronting llama-server + OpenAI endpoints (empty to disable)")
	flag.Parse()

	if *dataDir == "" {
		dir, err := os.UserConfigDir()
		if err != nil {
			dir, _ = os.UserHomeDir()
		}
		*dataDir = filepath.Join(dir, "relayLLM")
	}
	if err := os.MkdirAll(*dataDir, 0700); err != nil {
		slog.Error("failed to create data directory", "path", *dataDir, "error", err)
		os.Exit(1)
	}

	// Listener address: relayLLM picks where it binds. relay (if running)
	// learns the path via manifest registration; standalone clients dial it
	// directly. Default keeps the socket under data-dir so it's discoverable.
	if *socketPath == "" {
		*socketPath = filepath.Join(*dataDir, "relayllm.sock")
	}
	// Bearer token: relayLLM picks its own. Auto-generated if unset so the
	// listener is never unauthenticated. Under relay the token travels via
	// manifest registration. For standalone direct-client use, pin it with
	// --token / RELAY_LLM_TOKEN — we deliberately do not log the
	// auto-generated value so it doesn't end up in shipped log files.
	tokenAutoGenerated := *internalToken == ""
	if tokenAutoGenerated {
		*internalToken = generateBearerToken()
	}

	slog.Info("starting relayLLM",
		"socket", *socketPath,
		"dataDir", *dataDir,
		"tokenAutoGenerated", tokenAutoGenerated)

	sessionStore := NewSessionStore(filepath.Join(*dataDir, "sessions"))
	perms := NewPermissionManager()
	sessions := NewSessionManager(sessionStore, perms)
	sessions.SetDataDir(*dataDir)

	// Load provider + pty config up front. Terminal subsystem needs the pty
	// map to seed defaults before serving requests.
	openaiCfg, llamaCfg, piCfg, ptyCfg, err := LoadConfig(*dataDir, *openaiConfigPath)
	if err != nil {
		slog.Error("failed to load config", "error", err)
		os.Exit(1)
	}
	sessions.SetPiConfig(piCfg)
	if piCfg.BinaryPath != "" {
		slog.Info("pi binary configured", "path", piCfg.BinaryPath)
	}

	// Terminal subsystem.
	templateStore := NewTemplateStore(*dataDir)
	if err := templateStore.Load(ptyCfg); err != nil {
		slog.Error("failed to load terminal templates", "error", err)
	}
	terminalLogDir := filepath.Join(*dataDir, "terminal_logs")
	if err := os.MkdirAll(terminalLogDir, 0700); err != nil {
		slog.Error("failed to create terminal log directory", "path", terminalLogDir, "error", err)
		os.Exit(1)
	}
	terminalMgr := NewTerminalManager(templateStore, terminalLogDir)

	// Daily log GC. 30 days time-based with a 500 MB byte cap as a safety
	// net. Runs immediately at startup to catch up after a long downtime,
	// then once per 24h. Idle process — no shutdown coordination needed.
	go func() {
		const (
			sweepAge        = 30 * 24 * time.Hour
			sweepMaxBytes   = int64(500 * 1024 * 1024)
			sweepInterval   = 24 * time.Hour
		)
		for {
			if removed, err := sweepTerminalLogs(terminalLogDir, sweepAge, sweepMaxBytes); err != nil {
				slog.Warn("terminal log sweep failed", "error", err)
			} else if removed > 0 {
				slog.Info("terminal log sweep", "removed", removed)
			}
			time.Sleep(sweepInterval)
		}
	}()

	// Daily GC: drop headless sessions/*.json older than 7d, then drop
	// pi-sessions/*.jsonl whose piSessionId is no longer referenced by
	// any survivor (1h cushion so we don't race a live pi writer).
	go func() {
		const (
			headlessAge   = 7 * 24 * time.Hour
			piOrphanAge   = 1 * time.Hour
			sweepInterval = 24 * time.Hour
		)
		sessionsDir := filepath.Join(*dataDir, "sessions")
		piDir := filepath.Join(*dataDir, "pi-sessions")
		for {
			removed, livePi, err := sweepSessions(sessionsDir, headlessAge)
			if err != nil {
				slog.Warn("session sweep failed", "error", err)
			} else if removed > 0 {
				slog.Info("session sweep", "removed", removed)
			}
			if livePi != nil {
				if removed, err := sweepOrphanedPiSessions(piDir, livePi, piOrphanAge); err != nil {
					slog.Warn("pi orphan sweep failed", "error", err)
				} else if removed > 0 {
					slog.Info("pi orphan sweep", "removed", removed)
				}
			}
			time.Sleep(sweepInterval)
		}
	}()

	wsHub := NewWSHub(sessions, perms, terminalMgr)
	sessions.SetEventSink(wsHub)
	perms.SetEventSink(wsHub)

	// Wire terminal I/O to WebSocket hub.
	terminalMgr.SetOutputHandler(func(terminalID string, data []byte) {
		wsHub.SendToTerminal(terminalID, map[string]interface{}{
			"type":       "terminal_output",
			"terminalId": terminalID,
			"data":       base64.StdEncoding.EncodeToString(data),
		})
	})
	terminalMgr.SetExitHandler(func(terminalID string, exitCode int) {
		wsHub.SendToTerminal(terminalID, map[string]interface{}{
			"type":       "terminal_exit",
			"terminalId": terminalID,
			"exitCode":   exitCode,
		})
	})

	// The Claude CLI hook subprocess (runs as the user) dials our Unix
	// socket and authenticates with the internal token.
	sessions.SetHookSocket(*socketPath)
	sessions.SetHookToken(*internalToken)
	sessions.SetOllamaURL(*ollamaURL)

	if len(openaiCfg.Endpoints) > 0 {
		slog.Info("openai endpoints loaded", "count", len(openaiCfg.Endpoints), "names", openaiCfg.Names())
	}
	sessions.SetOpenAIConfig(openaiCfg)
	var llamaManager *LlamaServerManager
	if len(llamaCfg.Models) > 0 {
		llamaManager = NewLlamaServerManager(llamaCfg, *llamaServerPath)
		slog.Info("llama models configured", "count", len(llamaCfg.Models), "binary", llamaManager.binaryPath)
	}
	sessions.SetLlamaManager(llamaManager)

	var proxyRegistry *ProxyRegistry
	if len(openaiCfg.Endpoints) > 0 {
		proxyRegistry = NewProxyRegistry(openaiCfg)
	}
	sessions.SetProxyRegistry(proxyRegistry)

	// Llama wins on collision in the router's dispatch order; an OpenAI
	// endpoint sharing a llama alias would be unreachable via the router.
	if llamaManager != nil && proxyRegistry != nil {
		for _, ep := range openaiCfg.Endpoints {
			if llamaManager.HasAlias(ep.Name) {
				slog.Warn("router: openai endpoint name collides with llama alias; endpoint will be unreachable via the router", "name", ep.Name)
			}
		}
	}

	var routerAddr string
	if *routerPort != "" {
		routerAddr = ":" + *routerPort
	}
	relayRouter := StartRelayRouter(routerAddr, llamaManager, proxyRegistry)
	sessions.SetRouterPort(*routerPort)
	terminalMgr.SetPiOverlay(piCfg, sessions.piOverlayInputs)

	// Image generation via ComfyUI (optional).
	if *comfyuiURL != "" {
		comfyui := NewComfyUIClient(*comfyuiURL, *dataDir)

		// Discover available models. Retry for up to 30s to handle the case
		// where ComfyUI starts slower than relayLLM (common on cold boot).
		var checkpoints, loras []string
		{
			deadline := time.Now().Add(30 * time.Second)
			for time.Now().Before(deadline) {
				ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
				if err := comfyui.Ping(ctx); err == nil {
					slog.Info("ComfyUI connected", "url", *comfyuiURL)
					checkpoints, _ = comfyui.ListCheckpoints(ctx)
					loras, _ = comfyui.ListLoRAs(ctx)
					slog.Info("ComfyUI models discovered", "checkpoints", len(checkpoints), "loras", len(loras))
					cancel()
					break
				}
				cancel()
				time.Sleep(2 * time.Second)
			}
			if len(checkpoints) == 0 {
				slog.Warn("ComfyUI not reachable after 30s — image generation tool registered without model discovery", "url", *comfyuiURL)
			}
		}

		builtinTools := NewBuiltinToolRegistry()
		RegisterImageGenTool(builtinTools, comfyui, "/api/generated", checkpoints, loras)
		sessions.SetBuiltinTools(builtinTools)
	}

	mux := http.NewServeMux()
	RegisterSessionRoutes(mux, sessions)
	RegisterTerminalRoutes(mux, templateStore, terminalMgr)
	RegisterPermissionRoutes(mux, perms, sessions)
	RegisterModelRoutes(mux, *ollamaURL, openaiCfg, llamaManager, piCfg, sessions.piOverlayInputs)
	RegisterGeneratedImageRoutes(mux, *dataDir)
	RegisterStatusRoutes(mux, sessions, terminalMgr, llamaManager, startTime)
	mux.HandleFunc("/ws", wsHub.HandleUpgrade)

	// Build the handler chain. recoverMiddleware sits closest to the mux so it
	// catches panics from real handlers; bearerAuth sits in front so unauth
	// requests never reach a real handler (and never allocate a WS session).
	handler := bearerAuth(*internalToken, recoverMiddleware(mux))

	server := &http.Server{Handler: handler}

	if err := os.MkdirAll(filepath.Dir(*socketPath), 0o700); err != nil {
		slog.Error("failed to create socket parent dir", "path", *socketPath, "error", err)
		os.Exit(1)
	}
	// Remove any stale socket file from a previous crashed run.
	_ = os.Remove(*socketPath)
	listener, err := net.Listen("unix", *socketPath)
	if err != nil {
		slog.Error("failed to listen on socket", "path", *socketPath, "error", err)
		os.Exit(1)
	}
	if err := os.Chmod(*socketPath, 0o600); err != nil {
		slog.Warn("failed to chmod socket", "path", *socketPath, "error", err)
	}

	// Tell relay (if present) where to dispatch front-door traffic.
	// Standalone runs are a clean no-op. Run in a goroutine so a slow
	// relay-bridge round-trip doesn't delay the listener accepting traffic.
	go maybeRegisterManifest(*socketPath, *internalToken)

	// Graceful shutdown: drain HTTP requests, then clean up providers and terminals.
	go func() {
		sig := make(chan os.Signal, 1)
		signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)
		<-sig
		slog.Info("shutting down")

		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = server.Shutdown(ctx)
		_ = listener.Close()
		_ = os.Remove(*socketPath)
	}()

	slog.Info("listening", "socket", *socketPath)
	if err := server.Serve(listener); err != nil && err != http.ErrServerClosed {
		slog.Error("server error", "error", err)
		os.Exit(1)
	}

	// Server stopped — clean up background resources.
	sessions.StopAll()
	if relayRouter != nil {
		relayRouter.Close()
	}
	if llamaManager != nil {
		llamaManager.StopAll()
	}
	terminalMgr.StopAll()
	slog.Info("shutdown complete")
}

func envOrDefault(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

